# -*- coding: utf-8 -*-
"""momo_data_preprocess.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bfktsHtg5pBDho4UcwKDsSVlp7rlmNUj

## Error file 填回
"""

from datetime import datetime
import time
import pandas as pd
import os

f = pd.read_csv('/content/2024-01-08_momo_final.csv')

filein='/content/error_2024-01-08_07-56-29.txt'
with open (filein,'r',encoding='utf-8') as e_file:
    # 讀取文件內容
    content = e_file.read()
    # 輸出文件內容
    print(content)

line_number1 = 7  # 指定要讀取的行號
a1, a2, a3, a4, a5, a6, a7, a8, a9, a10 = [], [], [], [], [], [], [], [], [], []
with open(filein, 'r') as file:
    # 讀取文件的所有行
    lines = file.readlines()
    # 取得指定行號的內容
    # 品牌
    selected_line1 = lines[6]
    a1 = selected_line1.split(':')[1].strip().replace('[','').replace(']','').replace("'",'').split(',')
    print(a1)
    # 產品名稱
    selected_line2 = lines[7]
    a2 = selected_line2.split(':')[1].strip().replace('[','').replace(']','').replace("'",'').split(',')
    print(a2)
    # 類別1
    selected_line3 = lines[8]
    a3 = selected_line3.split(':')[1].strip().replace('[','').replace(']','').replace("'",'').split(',')
    print(a3)
    # 類別2
    selected_line4 = lines[9]
    a4 = selected_line4.split(':')[1].strip().replace('[','').replace(']','').replace("'",'').split(',')
    print(a4)
    # 類別3
    selected_line5 = lines[10]
    a5 = selected_line5.split(':')[1].strip().replace('[','').replace(']','').replace("'",'').split(',')
    print(a5)
    # 類別4
    selected_line6 = lines[11]
    a6 = selected_line6.split(':')[1].strip().replace('[','').replace(']','').replace("'",'').split(',')
    print(a6)
    # 折扣數
    selected_line7 = lines[12]
    a7 = selected_line7.split(':')[1].strip().replace('[','').replace(']','').replace("'",'').split(',')
    print(a7)
    # 原價
    selected_line8 = lines[13]
    a8 = selected_line8.split(':')[1].strip().replace('[','').replace(']','').replace("'",'').split(',')
    print(a8)
    # 數量
    selected_line9 = lines[14]
    a9 = selected_line9.split(':')[1].strip().replace('[','').replace(']','').replace("'",'').split(',')
    print(a9)
    # 折扣價
    selected_line10 = lines[15]
    a10 = selected_line10.split(':')[1].strip().replace('[','').replace(']','').replace("'",'').split(',')
    print(a10)

print(len(a1))

print(type(a1))


data = {
    "爬蟲日期": ['2024/01/08']*22,
    "爬蟲時間": ['07:53:26']*22,
    "活動檔期": ['00:00']*22,
    "品牌": a1,
    "產品名稱": a2,
    "產品類別1": a3,
    "產品類別2": a4,
    "產品類別3": a5,
    "產品類別4": a6,
    "折扣數": a7,
    "原價":  a8,
    "數量": a9,
    "折扣價": a10,
}

a = data['品牌']
b = data['產品名稱']
c = data['產品類別1']
d = data['產品類別2']
e = data['產品類別3']
f = data['產品類別4']
g = data['折扣數']

print(len(a),len(b),len(c),len(d),len(e),len(f),len(g))

h = data['原價']
i = data['數量']
j = data['折扣價']
print(len(h),len(i),len(j))

df = pd.DataFrame(data)

existing_df = pd.read_csv('/content/2024-01-08_momo_final.csv')
# 將新數據追加到現有 DataFrame
updated_df = pd.concat([existing_df, df], ignore_index=True)

# 寫入更新後的 DataFrame 到 CSV 文件
updated_df.to_csv('/content/2024-01-08_momo_final_2.csv', index=False)